### ISSUE TITLE
Removal of -headlessAuth in instructions

### ISSUE THREAD

**Issue by akumar95** [jenslys/autovod#11]
Hi!

First off, I wanted to say thanks for creating such an amazing vod automator. I've been using it for a couple of weeks and it's been a blessing.

I wanted to make this issue to update the instructions on getting this setup correctly. The author of youtubeuploader has removed the -headlessAuth parameter as of 22.03: https://github.com/porjo/youtubeuploader/issues/116

Per youtubeuploader instructions on headless servers: 

> To run the utility on a headless-server, generate the token file locally first, then simply copy the token file along with youtubeuploader and client_secrets.json to the remote host.

**Comment by jenslys** [comment]
Thanks for bringing this to my attention.
I have updated the readme and installer file with the new changes .https://github.com/jenslys/autovod/commit/3dd6d4c156f3d63046c19922db40ba356a22cb97


I might need to re-word it tho 😅
