### ISSUE TITLE
Not uploading Videos to YouTube

### ISSUE THREAD

**Issue by ZS-Andisch** [jenslys/autovod#12]
Hi,

everytime i stream, pm2 error log shows me this error message:

```
error: Error when writing to output: [Errno 32] Broken pipe, exiting
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

What can i do?

**Comment by akumar95** [comment]
I get this sometimes too and can't pinpoint the cause. I notice this happening either when I have more than one name when adding more than one twitch name with pm2. Are you doing the same? Also, what is your API usage? when I get Errno 32 I checked my API and it flew to 96%. Might be hitting the API limit for your designated Google account?

**Comment by jenslys** [comment]
https://console.cloud.google.com/iam-admin/quotas

**Comment by ZS-Andisch** [comment]
@jenslys thank you. On every Entrie 0% usage so no thats not the problem. The autovod doesnt upload any of my streams since i installed it.

**Comment by ZS-Andisch** [comment]
But the test video from the documentation worked

**Comment by jenslys** [comment]
Broken pipe means there is something wrong at the endpoint (Meaning youtube). Might be becuase the new Google TOS changes.

i would maybe try to start fresh and use the new instructions in the readme.

**Comment by akumar95** [comment]
Just bumping this to see if we can maybe troubleshoot this to see whats causing it? I have done an API audit through Google and my uploads are able to be publicized now. 

However, after running this for about 4-5 days and have finally ran into the dreaded Errno 32 Broken Pipe error. Looking at the API quota its at a comfortable 49.52% when it occurred.

**Comment by jenslys** [comment]
> Just bumping this to see if we can maybe troubleshoot this to see whats causing it? I have done an API audit through Google and my uploads are able to be publicized now.
> 
> However, after running this for about 4-5 days and have finally ran into the dreaded Errno 32 Broken Pipe error. Looking at the API quota its at a comfortable 49.52% when it occurred. Even after restarting pm2 its not able to pipe to Youtube. Would the fix be to restart the process and start anew?

What server provider are you using? Server resource exhaustion issue maybe?

**Comment by jenslys** [comment]
any updates @akumar95 @ZS-Andisch
