### ISSUE TITLE
How to add multiple channels?

### ISSUE THREAD

**Issue by akumar95** [jenslys/autovod#13]
Hi,

Apologies if this question seems silly but this is my first time setting up something like this so I am a bit ignorant.

I was wondering if it's possible to add multiple channels with AutoVOD or is it just single channel based? For instance there's a broadcaster that has a main channel and an alt. Would I be able to add both of their channels or is one instance only allowed?

Thanks

**Comment by jenslys** [comment]
I haven't tested,  but you could try to export another username env and start a new pm2 instance.
