### ISSUE TITLE
[Feature Request] - Stream title

### ISSUE THREAD

**Issue by Tritri89** [jenslys/autovod#17]
Hi, 

The script is working perfectly. I wondered how could change the title of the stream frome "STREAMER NAME + DATE" to the stream title on twitch. I see the variable : `VIDEO_TITLE="$STREAMER_NAME - $TIME_DATE" ` but I don't know how to get the stream name.

**Comment by jenslys** [comment]
I know [streamlink](https://streamlink.github.io/) can fetch the video title, but i am not sure how to implement it.
I might create and integrate a wrapper for the twitch API to fetch a streams title, when i have some more free time.

Thanks for the issue, i will keep this updated! 🚀

**Comment by jenslys** [comment]
@Tritri89 there is an open PR that implements both the stream title and game as variables. i have only tested parts of. I'm not able to fully test it until I'm finished with my exams in a few weeks.

But feel free to test it in the meantime.  👍🏻

PR: https://github.com/jenslys/autovod/pull/19

**Comment by Tritri89** [comment]
> @Tritri89 there is an open PR that implements both the stream title and game as variables. i have only tested parts of. I'm not able to fully test it until I'm finished with my exams in a few weeks.
> 
> But feel free to test it in the meantime. 👍🏻
> 
> PR: #19

I got over the youtube quotas for my tests (I had a few issue but I resolved it myself I think), but for now I can say that the curl command print the stream title and game. I'll try again tomorrow but I think it'll work ?

**Comment by jenslys** [comment]
👍🏻 

You can send in a request to increase your quota btw:
https://support.google.com/youtube/contact/yt_api_form?hl=en

**Comment by Tritri89** [comment]
> 👍🏻
> 
> You can send in a request to increase your quota btw: https://support.google.com/youtube/contact/yt_api_form?hl=en

Yep I know but to lazy to put all the info =D

So I did a new token for my personnal account for my tests. It didn't work :/. I put : $STREAM_TITLE - $STREAM_GAME in the VIDEO_TITLE field in the script, relaunched pm2, but it didn't get the name. I tried to troubleshoot but it's way over my level =D

But anyway take your time, in the meantime I can copy/paste the title, it's a few second ! Thanks for working on this !

**Comment by jenslys** [comment]
its seems my wrapper needs some more work.
The API dosent return a result on each call, so added that the curl command tries to retry if its empty

**Comment by Tritri89** [comment]
Welp indeed it doesn't work ! Maybe if I hardcode the name of the streamer in the curl command (like : https://twitch-api-wrapper.vercel.app/title/nameofthechannel ) ? 

Anyway take your time, for me I know I won't stream during the holiday, so nothing urgent from my side ! Good luck for your exams

**Comment by jenslys** [comment]
The issue is with my api-warpper, JS for me is fairly new, so this will take some trial and error.

Thanks!

**Comment by jenslys** [comment]
https://github.com/jenslys/autovod/pull/19 closes this
