### ISSUE TITLE
One or more required files are missing

### ISSUE THREAD

**Issue by MmeCromatique** [jenslys/autovod#41]
When using starting autovod.sh nothing hapens and the message `One or more requiered files are missing` is in the logs, except I have all files set and configured

**Steps to reproduce the behavior:**

1. Install the script with automatic installation
2. Run `pm2 start AutoVOD.sh --name StreamerNameHere`
3. Run `pm2 logs`

**Expected behavior**
Downloading and uploading of VODs

**Screenshots**
![image](https://user-images.githubusercontent.com/73028175/212405311-e8a9a404-6fc1-4e9a-bac0-6c7cfe41e942.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Additional context**
Running as a VM in Proxmox
I managed to upload the sample file

**Comment by jenslys** [comment]
Its looking for `request.token` and `client_secrets.json`.
Are both those files inside the autovod folder?

**Comment by MmeCromatique** [comment]
![image](https://user-images.githubusercontent.com/73028175/212411912-4df26b23-f6f4-42b3-91a9-015056a7661e.png)
They are not, I was told to put the json in .config, do I just copy both files in ?

**Comment by jenslys** [comment]
It should look like this:
![Screenshot 2023-01-13 at 21 22 28](https://user-images.githubusercontent.com/69081683/212412430-49d4d5f8-b4f5-4384-a25d-63261da07b8a.png)

both those files need to be placed inside the autovod folder.

**Comment by MmeCromatique** [comment]
![image](https://user-images.githubusercontent.com/73028175/212412477-22c3caba-010e-4116-a57c-b5343a711beb.png)
Seems to be working now (I placed the files)

**Comment by MmeCromatique** [comment]
Now I should just have to wait for a steam to start and we should be good, right ?

**Comment by jenslys** [comment]
yep, it checks the stream every 60 seconds to see if the stream is live.

**Comment by MmeCromatique** [comment]
Perfect, thank you very much for your time, I'm looking forward for the updated doc and instructions like for the form. 💕
