### ISSUE TITLE
Streamlink usage error with weird behavior

### ISSUE THREAD

**Issue by MmeCromatique** [jenslys/autovod#42]
When running, the script pushs out an error with an incressing amount of of "best"

**Steps to reproduce the behavior:**

1. Install the script with automatic installation
2. Run `pm2 start AutoVOD.sh --name StreamerNameHere`
3. Run `pm2 logs`
4. Wait more than 1 minute
5. See error

**Expected behavior**
Not outputting errors

**Screenshots**
![image](https://user-images.githubusercontent.com/73028175/212417009-fa98b68b-c892-4d2a-a467-fbd9705ca563.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Additional context**
Running as a VM in Proxmox

**Comment by jenslys** [comment]
i am not able to re-produce the error. are you using the newest version?

- delete your config
- run `git pull` while in the autovod folder
- create the config again `cp default.config monsieurplouf.config`

**Comment by jenslys** [comment]
update: was able to re-produce issue. debugging now

**Comment by jenslys** [comment]
just pushed a new commit that should fix it.

follow the steps above and let me know if it is resolved

**Comment by MmeCromatique** [comment]
![image](https://user-images.githubusercontent.com/73028175/212423826-01a1209d-601b-49b1-b338-0faa3fec9814.png)
Apparently fixed, I only get the expected error of no streams, thank you ❤
