### ISSUE TITLE
Username does not get defined properly

### ISSUE THREAD

**Issue by TheOngelma** [jenslys/autovod#5]
I've installed it properly, and I've verified that the script itself is working by hardcoding the username into AutoVOD.sh. When the username is hardcoded, the script runs like it's meant to be and uploads the VOD's to Youtube.

However when I run "pm2 start AutoVOD.sh --name usernamehere", and "pm2 save" after it, the script does not get the username. 

Tried running it both without sudo and in sudo, same result.

Tried also adding "$@" into AutoVOD.sh and it does not show any parameters.

Logs;

out.log

```
0|twitch_s | Starting AutoVOD...      

0|twitch_s | Using Twitch user:       

0|twitch_s |       

0|twitch_s |         

0|twitch_s | Checking twitch.tv/ for a stream.       

0|twitch_s | Trying again in 1 minute     
```   

error.log

```
0|twitch_s | error: No plugin can handle URL: twitch.tv/         

0|twitch_s | error: No plugin can handle URL: twitch.tv/       

0|twitch_s | error: No plugin can handle URL: twitch.tv/   
```     

I managed to fix this in my end by launching it with "pm2 start AutoVOD.sh --name usernamehere -- usernamehereonceagain" and then replacing "STREAMER_NAME=**$2**" in AutoVOD.sh with "STREAMER_NAME=**$1**" but would be still cool to know what exactly is going wrong, and if it's issue in script's end to get it fixed.

**Comment by jenslys** [comment]
Strange, I have changed back to the old way of passing the arguments.

Fetch the new changes and check the new instructions:
	https://github.com/jenslys/autovod#usage

**Comment by TheOngelma** [comment]
That seems to have fixed it, thanks.
