### ISSUE TITLE
403 Error on connection to Oauth

### ISSUE THREAD

**Issue by Leamnji** [jenslys/autovod#6]
Hello, I have been trying to get this to work on a raspberry to use for my VODs. I have managed to rewrite some things in the scripts since the names in the youtubeuploader repo have changed (files now called youtubeuploader_22.02_Linux_<env>.tar.gz)

My current issue is that I cant seem to get the Oauth to work. I have eveything setup so far but the actual connect to the API does seem to fail

![image](https://user-images.githubusercontent.com/49146534/167191429-39d44480-fb05-4e26-a0fa-6a1b9bd22ce2.png)

![image](https://user-images.githubusercontent.com/49146534/167191558-1da838c3-800f-47fc-93b4-6857febd7298.png)

**Comment by Leamnji** [comment]
Btw sorry for the error in german.

**Comment by Leamnji** [comment]
nvm issue on my part. Maybe you can add the fact that you need to add your own account as a test user in the API aswell ;) 
After that just had to empty browser cache and its working now!

**Comment by jenslys** [comment]
Readme updated https://github.com/jenslys/autovod/commit/dc702c2eaaa7e519c8206ddc793e3eaee3b3340a
