### ISSUE TITLE
[DOCKER] Volumes

### ISSUE THREAD

**Issue by THEDARKK** [jenslys/autovod#63]
Hello, Little question since we don't use the -v, where are the vods stored?

THANKS

**Comment by jenslys** [comment]
Currently they are stored inside the container:
![Screenshot 2023-04-05 at 14 00 38@2x](https://user-images.githubusercontent.com/69081683/230074271-2e78b72c-60a8-4586-9788-7e59c5f8d549.png)

Feel free to open a PR to introduce the option to change it
