### ISSUE TITLE
Stream variables not working

### ISSUE THREAD

**Issue by Johnnycyan** [jenslys/autovod#64]
**Describe the bug**
When trying to use stream variables it just returns "initial_title" instead of the actual title.

**To Reproduce**
1. Turn API calls on
2. Use the stream title variable
3. See that it does not actually pull the title

**Expected behavior**
The stream title should be pulled.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 2.1.0

**Comment by jenslys** [comment]
Can you share your config and pm2  logs?

**Comment by jenslys** [comment]
if you were using `local`, i have fixed this issue in the latest commit a51beff1059aa9779ebc3de50308b64a29f68d8e

**Comment by jenslys** [comment]
also added support for `rclone_dir` 0dad7d01b4d07467316cc103cb7261632fa13aa4
so i am closing this issue
