### ISSUE TITLE
[Feature request] automatic video scheduling for the "youtube" provider

### ISSUE THREAD

**Issue by ddomino007** [jenslys/autovod#69]
**Please Describe The Problem To Be Solved**
The Twitch affiliate agreement includes a timed exclusivity period (Affiliate agreement §2.2), which requires VODs and livestreams to be available only on Twitch for at least 24hrs. This means even with a project like autovod, there's still some manual labor - mainly with scheduling the VODs. 

**(Optional): Suggest A Solution**
youtubeuploader supports specifying when to schedule a video to (for that to work, the visibility has to be set to `private`). if autovod incorporated that in some way, it would make lives of streamers who maintain a VOD channel so much easier.

* Details of the technical implementation
If autovod supported automatically taking system time say, at the beginning and add 24hrs (or user specified time) and supply youtubeuploader with that information - this could help automate that compliance.
I can't find the specific CLI arg, but I know that if using the `metaJSON` argument, it's specified in the json as `publishAt`
If that's only supported while using the JSON file based metadata, I assume autovod would need to spit out a temporary JSON file somewhere and point youtubeuploader to it.
* Tradeoffs made in design decisions
Depending on the complexity of the code or any issues this might cause, removing the user specified offset feature and keeping it 24hrs only could be a thing that could be done as a last resort.
Not sure how OS specific would be pulling the local system timezone to be able to supply youtubeuploader with the correct timestamp, but if it proves troublesome it could be beneficial to just make the timezone user specifiable (and assume the user specified the timezone in accordance to how the system keeps the time).
* Caveats and considerations for the future
None at the moment.
EDIT: I have remembered autovod starts piping Streamlink into youtubeuploader at stream start, which means it's probably passing the metadata to YouTube at the very beginning. I have reflected the implications of this by rephrasing a bit.

**Comment by jenslys** [comment]
This should be fairly easy to add. 
I just have to think about the best way to add it:

1. By default publish 2 days later if youtube option is selected, then boolean var to turn it off?
2. Able to choose how many days you want delay upload  as a int var? default 0

**Comment by jenslys** [comment]
It seems Twitch has removed section 2.2 regarding the ability to re-upload the VOD.

Is this still a wanted feature?

**Comment by ddomino007** [comment]
I guess not, because it was meant as a solution after all :)
Hopefully they don't change it back haha
