### ISSUE TITLE
Download VODs

### ISSUE THREAD

**Issue by tbugatti** [jenslys/autovod#7]
There are many other tools out there to just download VODs but I'd love something I could spin up in Docker to just automatically watch a channel and download VODs.

**Comment by jenslys** [comment]
Hi, If you are looking for a docker container of this script, there is an open unfinished PR https://github.com/jenslys/autovod/pull/4 .  Feel free to finish the container.
But if you are just looking to download a VOD via docker, I found this alternative: https://github.com/lauwarm/docker-streamlink-recorder

**Comment by Fijxu** [comment]
@tbugatti You can use streamlink with the --output parameter, the process will not be terminated after the stream it's over, si it will record all the streams as longer the process is running ;)
