### ISSUE TITLE
Problem with STREAMER_TITLE and STREAMER_GAME variables

### ISSUE THREAD

**Issue by Azurz** [jenslys/autovod#74]
**Describe the bug**
I have the api that works and I receive the titles well, however on the youtube video there is an initial_title mark

**Screenshots**
![image](https://github.com/jenslys/autovod/assets/35930914/cbee5bdd-734d-4ca4-9666-f954bb19a5fc)
![image](https://github.com/jenslys/autovod/assets/35930914/894a7a8a-965f-4c69-87e5-1adf8651380f)

**Desktop (please complete the following information):**
 - OS: DEBIAN 12

**Comment by jenslys** [comment]
What does the logs say?

`pm2 logs`

**Comment by jenslys** [comment]
closing because no response from OP
