### ISSUE TITLE
Issue to prevent ADS to appear in VODs

### ISSUE THREAD

**Issue by skyiwii** [jenslys/autovod#77]
Hello, I have been using this script to upload twitch vods to youtube and for now it is being a successfully tool and working very well. The only problem is that where it says to prevent ads to appear in the VOD already uploaded it doesn't clarify very well where do I have to put the AuthO token with my Twitch account. Should I put it on the config streamlink file that is created with streamlink OR on the streamer config file within the streamlink parameters where I have to edit with the "nano" thing? Sorry if I'm using wrong this issues thread but I'm literally new to github and I have created this account to open this discuss to seek help, thanks

**Comment by jenslys** [comment]
yes you add the OAuth token: --twitch-api-header=Authorization=OAuth YOURCODEHERE to the STREAMLINK_OPTIONS field in the config file for the selected streamer.

nano is a tool to edit the config.
