### ISSUE TITLE
Youtube live support

### ISSUE THREAD

**Issue by timelf123** [jenslys/autovod#82]
**Please Describe The Problem To Be Solved**
support youtube.com/@channel/live urls

**(Optional): Suggest A Solution**

- config - don't infer username from filename (set them in a variable in the config - will allow for running several configs at once without risk of filename collision)

- config - allow passing full urls STREAM_URL, used in place of `$STREAM_SOURCE/$STREAMER_NAME`
or
- Add `URL_SUFFIX` - it will be empty by default, set to `/live` for `STREAM_SOURCE` youtube.com

```
if [ "$STREAM_SOURCE" = "youtube.com" ]; then
    URL_SUFFIX="/live"
else
    URL_SUFFIX=""
fi

streamlink $STREAM_SOURCE/$STREAMER_NAME$URL_SUFFIX
```

**Comment by jenslys** [comment]
This seems like it should be 2 separate issues:
1. Support for YouTube live
2. Move away from filename based config, and use a variable.

Solution:
1. This would be fairly easily to implement.
2. While having the streamer name assigned inside the config file would work for docker, it does not when running it via PM2
	1. In what scenario would a person need multiple configs for the same user? if they switch from e.g twitch -> kick after x amount of hours?

**Comment by timelf123** [comment]
>In what scenario would a person need multiple configs for the same user? if they switch from e.g twitch -> kick after x amount of hours?
Yep some users stream on different platforms at different times, for whatever reason, and sometimes their name is identical

**Comment by jenslys** [comment]
considering this as completed in https://github.com/jenslys/autovod/pull/83
